# Generated by Django 4.2 on 2023-08-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="post_data_model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Post_ID_field", models.IntegerField(unique=True)),
                ("title_field", models.CharField(max_length=100)),
                ("content_field", models.CharField(max_length=200)),
                ("User_ID_field", models.CharField(max_length=50)),
                ("Time_field", models.TimeField()),
            ],
        ),
    ]
