# Generated by Django 4.2 on 2023-08-17 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0003_userclass"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userclass",
            options={
                "permissions": [
                    ("user", "User"),
                    ("manager", "Manager"),
                    ("admin", "Admin"),
                    ("test", "TEst"),
                ]
            },
        ),
    ]
